### ISSUE TITLE
Support for YouTube Clips

### ISSUE THREAD

**Issue by leungbk** [JakeMiki/twitch-clip-queue#14]
Presently, the clip queue does not handle YouTube Clips such as `https://www.youtube.com/clip/Ugkx_hZcYY2GAabdchd4Tr9GrJndwdtGD1OY`. The YouTube Data API does not presently provide any meaningful support for acquiring the parameters necessary to construct an embed URL such as `https://www.youtube.com/embed/AynwCXZp8ZI?clip=Ugkx_hZcYY2GAabdchd4Tr9GrJndwdtGD1OY&amp;clipt=EIih5AkYoJblCQ`.

It is possible to acquire the aforementioned embed URL by performing a GET request on `https://www.youtube.com/clip/Ugkx_hZcYY2GAabdchd4Tr9GrJndwdtGD1OY` and regex-ing the HTML provided in the response. However, I am not sure if this violates the YouTube Data API's Terms of Service.

Would you accept a PR that adds support for YouTube Clips using the procedure I have described?

**Comment by leungbk** [comment]
Proper API support for Clips has been requested upstream, but there is no timeline: https://issuetracker.google.com/issues/269627289

**Comment by 0x263b** [comment]
The embed URL is in the HTML response, do a regex match for `/<meta property=\"og:video:url\" content=\"(\S+)\">/`. 

It's more cumbersome than a dedicated API but it's doable.
