### ISSUE TITLE
Broken clips due to autoplay

### ISSUE THREAD

**Issue by gillsB** [jakemiki/twitch-clip-queue#19]
Lots of problems with twitch clips lately. In some testing I did last night it seems to be from autoplay. 

Turning it off fixes the active clip if not loading. And turning it off stops it from happening in the first place on going to next clip.

It seems like the when autoplay is turned on it either doesn't attempt the twitch api call or it doesn't receive anything back (nothing prints to console)

**Comment by gillsB** [comment]
Further, if you find a broken twitch clip, turn autoplay off so it loads the video and plays the video. Even then if you turn autoplay back on it breaks the clip instantly (goes back to a blank 0 second video placeholder).

**Comment by gillsB** [comment]
Seems to be fixed. At least works for the clips I originally tested with. Thank you.

**Comment by jakemiki** [comment]
Hi, thanks for reporting the issue. Autoplay for twitch clips relies on undocumented, unofficial behaviour so sadly it can break at any moment. Hope it works without issues at least for some time now :smile: 

If you notice anything weird with autoplay clips feel free to reopen this issue, as it might be related to the fix.
